In [17]:
import numpy as np

In [18]:
marks = np.array([
    [78, 85, 90],
    [45, 60, 55],
    [88, 92, 95],
    [30, 40, 35],
    [65, 70, 75]
])

Determine the shape of the array
Find the Total number of elements
Identify the data type of the elements

In [19]:
marks.shape 
marks.size
marks.dtype

dtype('int64')

Extract all marks for the 2nd student.

In [20]:
marks[1]

array([45, 60, 55])

Extract all marks for the 3rd subject across all students.

In [21]:
marks[:, 2]

array([90, 55, 95, 35, 75])

Find the specific mark for Student 1 in Subject 2.

In [22]:
marks[0, 1]

np.int64(85)

Calculate the average marks for each student.

In [23]:
student_avg = marks.mean(axis=1)

Calculate the average marks for each subject.

In [24]:
subject_avg = marks.mean(axis=0)

Identify and display students whose average marks are ≥ 80.

In [25]:
top_students = np.where(student_avg >= 80)[0]
top_students

array([0, 2])

The college decides to add 5 grace marks to every subject for every student.

In [26]:
marks += 5

Create a status matrix where:
Mark ≥ 50 → 1 (Pass)
Mark < 50 → 0 (Fail)

In [27]:
status = np.where(marks >= 50, 1, 0)

To standardize failing grades, replace all marks below 40 with a value of 0.

In [28]:
marks[marks < 40] = 0

 Grade Allocation Apply a grading system based on the Student
Average

In [29]:
grades = np.where(student_avg >= 85, 10,
         np.where(student_avg >= 70, 8,
         np.where(student_avg >= 50, 6, 0)))

Create a backup of the marks array.
Modify the original array (e.g., set marks[0, 0] = 0).
Check if the backup array changed or remained original

In [31]:
backup = marks.copy()
marks[0, 0] = 0
backup[0,0]

np.int64(83)