In [56]:
import numpy as np


In [57]:
electricity = np.array(np.random.randint(120, 651, size = [4, 7]))
electricity

array([[288, 455, 637, 556, 352, 300, 300],
       [533, 560, 507, 273, 601, 269, 340],
       [186, 134, 136, 367, 571, 364, 128],
       [297, 273, 526, 536, 303, 419, 337]], dtype=int32)

In [58]:
print(np.shape(electricity))


(4, 7)


Task 2: Calculate average electicity usage of every hostel

In [59]:
avg = electricity.mean(axis=1)
print(avg)


[412.57142857 440.42857143 269.42857143 384.42857143]


Task C1: Create a new array penalized usage such that:
-> values > 550 -> multiplied by 1.20
-> all other values remain unchanged

In [60]:
penalized = np.where(electricity > 550, electricity * 1.20, electricity)
print(penalized)

[[288.  455.  764.4 667.2 352.  300.  300. ]
 [533.  672.  507.  273.  721.2 269.  340. ]
 [186.  134.  136.  367.  685.2 364.  128. ]
 [297.  273.  526.  536.  303.  419.  337. ]]


Task D1: compare each hostel's daily usage with its own weekly average . Create a boolean matrix where:
->True : above hostel average
->False : below or equal to hostel average

In [61]:
boolean = electricity > avg[:, np.newaxis]
print(boolean)

[[False  True  True  True False False False]
 [ True  True  True False  True False False]
 [False False False  True  True  True False]
 [False False  True  True False  True False]]


Task E1: reshape the electricity data into a single row representing weekly usage (shape : 1x28)

In [62]:
electricity = electricity.reshape(1, 28)
print(electricity)

[[288 455 637 556 352 300 300 533 560 507 273 601 269 340 186 134 136 367
  571 364 128 297 273 526 536 303 419 337]]


Task E2: reshape the same data into 2 rows and 14 columns. Ensure no data is lost or duplicated

In [63]:
electricity = electricity.reshape(2, 14)
print(electricity)

[[288 455 637 556 352 300 300 533 560 507 273 601 269 340]
 [186 134 136 367 571 364 128 297 273 526 536 303 419 337]]


Task F1: 
-> create ref_backup = electricity
-> create safe_backup = electricity.copy()
-> modify one value in the original electicity array
-> observe which backups change

In [64]:
ref_backup = electricity
safe_backup = electricity.copy()
electricity[0][0] = 0
print(ref_backup)
print(safe_backup)

[[  0 455 637 556 352 300 300 533 560 507 273 601 269 340]
 [186 134 136 367 571 364 128 297 273 526 536 303 419 337]]
[[288 455 637 556 352 300 300 533 560 507 273 601 269 340]
 [186 134 136 367 571 364 128 297 273 526 536 303 419 337]]
