In [1]:
import numpy as np

headphone = np.array([10, 15, 8, 12])
smartwatches = np.array([5, 7, 4, 6])
speakers = np.array([2, 3, 2, 4])
days = np.array(["Mon", "Tue", "Wed", "Thu"])
print("days: ", days)
print("Headphone: ", headphone)
print("Smartwatches sold: ", smartwatches)
print("Speakers sold: ", speakers)

days:  ['Mon' 'Tue' 'Wed' 'Thu']
Headphone:  [10 15  8 12]
Smartwatches sold:  [5 7 4 6]
Speakers sold:  [2 3 2 4]


In [2]:
costprice = np.array([1000, 3000, 2500])
print("Cost Price of items", costprice)


Cost Price of items [1000 3000 2500]


In [3]:
sales = np.array([headphone, smartwatches, speakers])
new_array = sales + 2
new_array

array([[12, 17, 10, 14],
       [ 7,  9,  6,  8],
       [ 4,  5,  4,  6]])

In [4]:
revenue = new_array * costprice[:, np.newaxis]
revenue

array([[12000, 17000, 10000, 14000],
       [21000, 27000, 18000, 24000],
       [10000, 12500, 10000, 15000]])

In [5]:
smartwatches_sales = sales[1]
smartwatches

array([5, 7, 4, 6])

In [6]:
speakers_thur = sales[2][3]
speakers_thur

np.int64(4)

In [7]:
sub_array = sales[0:2, 0:2]
sub_array

array([[10, 15],
       [ 5,  7]])

In [8]:
flat_sales = sales.reshape(-1)
flat_sales

array([10, 15,  8, 12,  5,  7,  4,  6,  2,  3,  2,  4])

In [9]:
sales2x6 = sales.reshape(2, 6)
sales2x6

array([[10, 15,  8, 12,  5,  7],
       [ 4,  6,  2,  3,  2,  4]])

In [10]:
discounts = np.linspace(0, 100, 10)
discounts

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [11]:
predicted_sales = np.random.randint(0, 21, size = (3 , 4))
predicted_sales

array([[20, 16, 10, 18],
       [13, 20, 12,  7],
       [ 0, 15, 12, 12]], dtype=int32)

In [12]:
random_values = np.random.rand(5)
random_values

array([0.74006301, 0.4870231 , 0.21096185, 0.26924419, 0.96879407])

In [13]:
total_sales = np.sum(sales)
total_sales

np.int64(78)

In [14]:
product_total = np.sum(sales, axis = 1)
product_total

array([45, 22, 11])

In [15]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(np.sum(arr , axis = 0))

[5 7 9]


In [16]:
arr2 = np.array([4, -2, 94, 0, -4, -11, 12])
res = np.where(arr2 > 0, arr2, 0)              #where function arguments are (conditions, true, false) : like ternary operator
res

array([ 4,  0, 94,  0,  0,  0, 12])

In [17]:
parity = np.where(arr2 & 1, "odd", "even")
parity

array(['even', 'even', 'even', 'even', 'even', 'odd', 'even'], dtype='<U4')

In [18]:
marks = np.array([45, 78, 32, 90, 55])
status = np.where(marks < 50, "fail", "pass")
status

array(['fail', 'pass', 'fail', 'pass', 'pass'], dtype='<U4')

In [19]:
mat = np.array([[10, 60, 30],
               [80, 20, 90]])
res2 = np.where(mat < 50, "fail", "pass")
res2

array([['fail', 'pass', 'fail'],
       ['pass', 'fail', 'pass']], dtype='<U4')

In [20]:
marks2 = np.array([[78, 85, 90],
           [45, 60, 55],
           [88, 92, 95],
           [30, 40, 35],
           [65, 70, 75]])
marks2

array([[78, 85, 90],
       [45, 60, 55],
       [88, 92, 95],
       [30, 40, 35],
       [65, 70, 75]])

In [21]:
print(marks2.shape,
marks2.size,
marks2.dtype)

(5, 3) 15 int64


In [22]:
print(marks2[1])
print(marks2[:, 2])
print(marks2[0][2])

[45 60 55]
[90 55 95 35 75]
90


In [23]:
avr = (np.sum(marks2, axis = 1) / 3)
print(np.sum(marks2, axis = 0) / 5)
avr

[61.2 69.4 70. ]


array([84.33333333, 53.33333333, 91.66666667, 35.        , 70.        ])

In [24]:
print(np.where(avr >= 80, "topper", "below"))


['topper' 'below' 'topper' 'below' 'below']


In [25]:
status = np.where(marks2 < 50, "Fail", "Pass")
status

array([['Pass', 'Pass', 'Pass'],
       ['Fail', 'Pass', 'Pass'],
       ['Pass', 'Pass', 'Pass'],
       ['Fail', 'Fail', 'Fail'],
       ['Pass', 'Pass', 'Pass']], dtype='<U4')

In [26]:
marks2 = np.where(marks2 < 40, 0, marks2)
marks2

array([[78, 85, 90],
       [45, 60, 55],
       [88, 92, 95],
       [ 0, 40,  0],
       [65, 70, 75]])

In [ ]:
grade = np.where(marks2 < 50, 0, np.where(marks2 < 70, 6, np.where(marks2 < 85 , 8, 10)))          #nested condition like if else nesting using where
grade

array([[ 8, 10, 10],
       [ 0,  6,  6],
       [10, 10, 10],
       [ 0,  0,  0],
       [ 6,  8,  8]])

In [29]:
backup = marks2.copy()
backup[0, 0] = 0
print(marks2)
print(backup)

[[78 85 90]
 [45 60 55]
 [88 92 95]
 [ 0 40  0]
 [65 70 75]]
[[ 0 85 90]
 [45 60 55]
 [88 92 95]
 [ 0 40  0]
 [65 70 75]]
